### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by lstmemery** [davidklaing/vizit#16]
Other users of this Shiny app are not going much of our documentation. I think we should:

1. Change the name of this project (Possibly edxviz)
2. Store the unnecessary documentation in a private repo just for us.

**Comment by lstmemery** [comment]
I'm not going to do the rename today. Here's the external docs repo: https://github.com/lstmemery/ubc_mds_capstone_mooc_docs

**Comment by davidklaing** [comment]
Things that would happen if we change the name:

1. The [init.d script](https://github.com/laingdk/mooc_capstone_public/blob/cd4e123d3f2f1831f0af6cfee355b64cfc091324/edxviz) will have a broken path.
2. The [docker-compose.yml file](https://github.com/laingdk/mooc_capstone_public/blob/da517c0eea23c82de57a3b882f1df5c82c64d90b/docker-compose.yml) will have volumes with broken paths.
3. The [deployment docs](https://github.com/laingdk/mooc_capstone_public/blob/90305084319f4718fe0281f75773c1f2ac97c23a/docs/deployment.md) will have broken paths.
4. The [Dockerfile](https://github.com/laingdk/mooc_capstone_public/blob/4aa0a3f312fa243b0ccd69cd6709f36719a840ca/Dockerfile) will have a broken path.
5. The [deployment walkthrough in the bookdown documentation](https://github.com/laingdk/mooc_capstone_public/blob/9e6eb648ae4300df3e5daf5e29966a8e7a6d9eb0/docs/edx_viz_documentation/15-deployment_walkthrough.Rmd) will have a broken path.
6. The [rendered deployment walkthrough html](https://github.com/laingdk/mooc_capstone_public/blob/b3132aea11a9ae3dc51611f74e3c454e116f2a28/docs/edx_viz_documentation/_book/deployment-walkthrough.html) will need to be updated after the bookdown Rmd is updated.
7. The [search index in the bookdown documentation](https://github.com/laingdk/mooc_capstone_public/blob/b3132aea11a9ae3dc51611f74e3c454e116f2a28/docs/edx_viz_documentation/_book/search_index.json) will need to be updated after the bookdown Rmd is updated.
8. The links in Matt's blog post will be broken.
9. Links from any of the team members' sites/resumes/etc will be broken.
10. Links that have been sent to people within and outside UBC will no longer work.
11. We would want to change some of the naming (any reference to `edxviz`, for example) in the documentation.
